ALTER TABLE Horses ADD CONSTRAINT stableFK 
FOREIGN KEY (stableID) REFERENCES Stables(stableID) 
    ON DELETE RESTRICT
    ON UPDATE CASCADE;

ALTER TABLE Horses ADD CONSTRAINT trainerFK 
FOREIGN KEY (trainerID) REFERENCES RacingPersons(personID) 
    ON DELETE SET NULL
    ON UPDATE CASCADE;

ALTER TABLE Horses ADD CONSTRAINT horseOwnerFK 
FOREIGN KEY (horseOwnerID) REFERENCES RacingPersons(personID) 
    ON DELETE CASCADE
    ON UPDATE RESTRICT;